{% set name = "pypistats" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypistats-{{ version }}.tar.gz
  sha256: 91a69e68e7a73ad82d574a3a95957632322e2273ae920dec2a35db4be4c0fb85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - pypistats = pypistats.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - hatch-vcs
    - hatchling
  run:
    - python >=3.7
    - httpx >=0.19
    - platformdirs
    - prettytable >=2.4
    # pytablewriter[html]
    - dominate >=2.1.5,<3
    - pytablewriter >=0.63
    - python-dateutil
    - python-slugify
    - termcolor
    - importlib-metadata

test:
  imports:
    - pypistats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hugovk/pypistats
  summary: Python interface to PyPI Stats API https://pypistats.org/api
  dev_url: https://github.com/hugovk/pypistats
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
